### ISSUE TITLE
Add additional arbitrator address

### ISSUE THREAD

**Issue by Gathin23** [TalentLayer/talentlayer-sdk#11]
Requesting to add 0x05a782977eD60B53148bf6cCCC435812073909Bb to arbitrator addresses for testing purposes

**Comment by 0xRomain** [comment]
need to be done manually in this case: 
- clone the sdk repo
- use your addres here: https://github.com/TalentLayer/talentlayer-sdk/blob/develop/packages/client/src/config.ts#L35
- follow readme instructions to use your local sdk version in starterkit: https://github.com/TalentLayer/talentlayer-sdk/blob/develop/README.md#build-the-package-on-your-own
