### ISSUE TITLE
Bug: Mismatching case to add abitrator contract address

### ISSUE THREAD

**Issue by Gathin23** [TalentLayer/talentlayer-sdk#7]
```
public async updateArbitrator(
    address: `0x${string}`,
  ): Promise<TransactionHash> {
    const chainConfig = getChainConfig(this.wallet.chainId);
    const contract = chainConfig.contracts["talentLayerArbitrator"];
    const allowedArbitrators = [zeroAddress, contract.address.toLowerCase()];

    console.log("SDK: allowedArbitrators", allowedArbitrators);

    if (!allowedArbitrators.includes(address)) {
      throw new Error(`Invalid Arbitrator: ${address}`);
    }

    const tx = await this.wallet.writeContract(
      "talentLayerPlatformId",
      "updateArbitrator",
      [this.platformID, address, ""],
    );

    return tx;
  }
```

The .toLowerCase is causing error to start with dispute kit resolution

![image](https://github.com/TalentLayer/talentlayer-sdk/assets/94786511/c8022e79-9da7-4713-bcc2-6d8e0af8acdb)

**Comment by pranav-singhal** [comment]
Here is what I think we should do

1. create a function for getting all allowed arbitrators ( @0xRomain -can we get that list via graph?)

2. expose that function publicly, and use it internally here

**Comment by 0xRomain** [comment]
that would have been better yes, but we don't have that yet, it miss an event and subgraph management. I will add for the future. 
What we can do now is still have a function from the sdk to get all allowed arbitrators but hardcoded in config by chain.

**Comment by pranav-singhal** [comment]
makes sense
Ill track that as an improvement in a separate ticket then
